general:
  health:
    heartbeat: 1000.0

planners:
  rate: 100.0
  default_planner: orca
  planner_name_list:
    - spotturn
    - orca
    - pure_pursuit
  planner_name_plugin_mapping:
    - mrp_motion_planner::SpotTurn
    - mrp_orca::MotionPlanner
    - mrp_pure_pursuit::MotionPlanner