version: '3'
services:
  ros_dev:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
    privileged: true
    volumes:
      - ${PWD}:/root/multi_robot_playground2/src/multi-robot-playground
    network_mode: host
    ports:
      - 9090:9090
      - 11345:11345
    restart: always
    command: bash -c 'source /opt/ros/humble/setup.bash && ros2 launch rosbridge_server rosbridge_websocket_launch.xml'