general:
  health:
    heartbeat: 1000.0

planners:
  default_planner: orca
  planner_name_list:
    - spotturn
    - orca
  planner_name_plugin_mapping:
    - mrp_motion_planner::SpotTurn
    - mrp_orca::MotionPlaner