general:
  health:
    heartbeat: 1000.0

planners:
  default_planner: rvo
  planner_name_list:
    - spotturn
    - rvo
  planner_name_plugin_mapping:
    - mrp_motion_planner::SpotTurn
    - mrp_motion_planner::RVO