paths:
  robot:
    - position:
        x: 2.0
        y: 0.0
        z: 0.0
      orientation:
        r: 0.0
        p: 0.0
        y: 3.14

  robot0:
    - position:
        x: 0.0
        y: 0.0
        z: 0.0
      orientation:
        r: 0.0
        p: 0.0
        y: 0.0
  
  robot1:
    - position:
        x: 1.0
        y: -1.0
        z: 1.57
      orientation:
        r: 0.0
        p: 0.0
        y: 0.0

  robot2:
    - position:
        x: 1.0
        y: 1.0
        z: -1.57
      orientation:
        r: 0.0
        p: 0.0
        y: 0.0