paths:
  robot:
    - position:
        x: 0.0
        y: 0.0
        z: 0.0
      orientation:
        r: 0.0
        p: 0.0
        y: 0.0

    - position:
        x: 2.0
        y: 0.0
        z: 0.0
      orientation:
        r: 0.0
        p: 0.0
        y: 0.0