world:
  package: multi_robot_playground
  path: worlds/empty.world

map:
  min_x: -1
  max_x: 1
  min_y: -1
  max_y: 1

robots:
  randomise_pose: false
  # Choose among one of these global planner:
  # - hungarian
  global_planner: hungarian
  models:
    - name: robot0
      namespace: robot0
      radius: 0.2
      x: 0
      y: 0
      yaw: 0
      model_package: modified_turtlebot3_gazebo
      path_to_model: models/turtlebot3_burger/model.sdf
      urdf_package: turtlebot3_description
      urdf_path: urdf/turtlebot3_burger.urdf

    - name: robot1
      namespace: robot1
      radius: 0.2
      x: 0
      y: 1
      yaw: 0
      model_package: modified_turtlebot3_gazebo
      path_to_model: models/turtlebot3_burger/model.sdf
      urdf_package: turtlebot3_description
      urdf_path: urdf/turtlebot3_burger.urdf

    # - name: robot2
    #   namespace: robot2
    #   radius: 0.2
    #   x: 0
    #   y: -1
    #   yaw: 0
    #   model_package: modified_turtlebot3_gazebo
    #   path_to_model: models/turtlebot3_waffle/model.sdf
    #   urdf_package: turtlebot3_description
    #   urdf_path: urdf/turtlebot3_waffle.urdf

      