world:
  package: multi_robot_playground
  path: worlds/empty.world

robots:
  randomise_pose: false
  models:
    - name: robot0
      namespace: robot0
      x: 0
      y: 0
      yaw: 0
      model_package: modified_turtlebot3_gazebo
      path_to_model: models/turtlebot3_burger/model.sdf